version: '3.8'

services:
  neo4j:
    image: neo4j:5.18.0
    container_name: neo4j_graphrag
    ports:
      - "7474:7474" # HTTP UI
      - "7687:7687" # Bolt port
    environment:
      - NEO4J_AUTH=neo4j/password123
      # Para o GraphRAG usando Langchain APOC é altamente recomendado:
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - ./data/neo4j:/data
    restart: unless-stopped
